### ISSUE TITLE
Google.com is different on your demo

### ISSUE THREAD

**Issue by gaalos** [dehlirious/PocketProxy#10]
Hey 
on  your demo we got 
![image](https://github.com/dehlirious/PocketProxy/assets/32361668/ff348c83-b64b-4966-ab5c-ae53be41fe80)
On my
![image](https://github.com/dehlirious/PocketProxy/assets/32361668/94cef235-8d19-4c74-aa72-e0213bd55590)

I got policy all time i use google search

**Comment by dehlirious** [comment]
Yeah, I wouldn't be able to classify this as an issue. You would appear to be located outside of the U.S, with another language which google can identify likely via your IP / cookies. Through the proxy script, it see's it as an american IP, English speaker. Please correct me if you think I'm mistaken!

**Comment by gaalos** [comment]
@dehlirious  do you have discord on something

**Comment by dehlirious** [comment]
> @dehlirious  do you have discord on something 

[![discord](https://img.shields.io/badge/contact-me-blue?logo=discord&logoColor=white)](https://discordapp.com/users/648079846857244684)
