### ISSUE TITLE
Adding s to https when it's already https.

### ISSUE THREAD

**Issue by gaalos** [dehlirious/PocketProxy#3]
I set : 
 $this->httpvariable = "https";

But 
at line 61
define("PROXY_PREFIX", $this->httpvariable . (isset($_SERVER["HTTPS"]) ? "s" : "") . "://" . $this->prefixHost . "" //.$prefixPort //was removed because it displayed port 80 and i haven'>
                 . $_SERVER["SCRIPT_NAME"] . "?");

You add s when $_SERVER["HTTPS"] exist.
that create someting with httpss://site.....

**Comment by dehlirious** [comment]
Wow! That's embarrassing, oddly enough I already fixed this issue on my own server but never pushed a commit to the GitHub repository!

**Comment by dehlirious** [comment]
https://github.com/dehlirious/PocketProxy/pull/5

**Comment by gaalos** [comment]
@dehlirious  did not see your comment thx for your fix
