### ISSUE TITLE
Captcha issue

### ISSUE THREAD

**Issue by gaalos** [dehlirious/PocketProxy#4]
Hi 
I got :
![image](https://user-images.githubusercontent.com/32361668/235161239-f538a2d4-dca3-4a00-b487-19aeda5d4f67.png)

I did not add to suspicious website
I log i got:

"PHP Fatal error:  Uncaught Error: Call to undefined function Gregwar\\Captcha\\imagecreatetruecolor() in /var/www/PocketProxy/Captcha/AIO-Captcha.php:36\nStack trace:\n#0 /var/www/PocketProxy/pocketproxy.php(478): Gregwar\\Captcha\\CaptchaBuilder->build()\n#1 {main}\n  thrown in /var/www/PocketProxy/Captcha/AIO-Captcha.php on line 36, referer: https://mesh.minouche.club/pocketproxy.php"

**Comment by dehlirious** [comment]
Sorry for not getting to you sooner!
I'll be sure to update the code to make sure of a few necessities. 

You need the PHP GD library! That is the issue, unfortunately! 
If you want, I can try and find an alternative.
