### ISSUE TITLE
Some ressources are not loaded with proxy

### ISSUE THREAD

**Issue by gaalos** [dehlirious/PocketProxy#7]
As you can see some ressources are not proxified 
![image](https://github.com/dehlirious/PocketProxy/assets/32361668/c5131632-f41f-4a41-86ef-b5d9dd369de5)

Website test :
https://tastewp.com/

**Comment by dehlirious** [comment]
This has been an issue, I've done quite a lot to try and stop it but unfortunately I haven't quite succeeded yet. I'll have to try and give it another shot, next up I'm going to have to try and process javascript or something.

Same issue exists on YouTube.com , I spent a good amount of time trying to use javascript to get javascript to intercept the requests but to no avail.

**Comment by dehlirious** [comment]
Fixed the issue [here](https://github.com/dehlirious/PocketProxy/commit/b77845949e3cf56b75c778b141cf52c0f0ca6879)
Open a new issue or start a discussion if you have further issues or if you notice thing's not loading through the proxy!
